### ISSUE TITLE
Fix task drag & drop capabilities on mobile devices as well

### ISSUE THREAD

**Issue by devark28** [KevinRebakure/ToDo#7]
find a way for the npm dnd package and dnd-html5-backend to be able to work on mobile devices

**Comment by KevinRebakure** [comment]
Since doing the responsiveness of this little todo app wasn't in my mind from the start, I didn't commit to actively maintain this project, as it was meant to be a quick hands-on exercise. 

This looks like a good challenge though.

I read a little about the **React DnD** library which was used for drag and drop feature, and it turns out that it doesn't support [touch events](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events) for touch screen devices like mobile phones. However, there's a dedicated back-end React DnD package that you can find [here](https://react-dnd.github.io/react-dnd/docs/backends/touch) which have the added support for **touch events**. 

I can't promise to work on it soon or later. But with that reference, I think I can welcome anyone who's interested to work on this challenge. 

Let's leave this issue open for future reference. I still believe that it's worth a try though.💪

Thanks for pointing that out!!⭐

**Comment by KevinRebakure** [comment]
> find a way for the npm dnd package and dnd-html5-backend to be able to work on mobile devices

done✅...
